export type IndustrialCompany = {
  rank: number;
  ticker: string;
  name: string;
  industry: string;
  marketCap: number;
  revenue: number;
  dayChange: number;
  priceTarget: number;
  currentPrice: number;
  revenueForecast: number[];
  stockForecast: number[];
  topClients: string[];
  futureCustomers: string[];
};

export type IndustrialDeal = {
  id: string;
  acquirer: string;
  target: string;
  ticker?: string;
  value: string;
  date: string;
  status: string;
  rationale: string;
};

export const topIndustrialCompanies: IndustrialCompany[] = [
  {
    rank: 1,
    ticker: "CAT",
    name: "Caterpillar Inc.",
    industry: "Construction & Mining Machinery",
    marketCap: 413.36,
    revenue: 70.76,
    dayChange: 0.2,
    currentPrice: 897.45,
    priceTarget: 931.35,
    revenueForecast: [70.8, 73.5, 77.1, 81.4],
    stockForecast: [897.45, 912, 931.35, 958],
    topClients: ["United Rentals", "Rio Tinto", "BHP", "Freeport-McMoRan", "U.S. infrastructure contractors"],
    futureCustomers: ["Battery-metals miners", "Data-center backup power operators", "Autonomous mine operators"],
  },
  {
    rank: 2,
    ticker: "GE",
    name: "GE Aerospace",
    industry: "Aerospace & Defense",
    marketCap: 310.03,
    revenue: 48.31,
    dayChange: -1.81,
    currentPrice: 292,
    priceTarget: 316,
    revenueForecast: [48.3, 52.6, 57.8, 62.4],
    stockForecast: [292, 305, 316, 338],
    topClients: ["Boeing", "Airbus", "U.S. Department of Defense", "Delta Air Lines", "Emirates"],
    futureCustomers: ["Next-gen narrowbody programs", "Defense propulsion primes", "Sustainable aviation fuel fleets"],
  },
  {
    rank: 3,
    ticker: "GEV",
    name: "GE Vernova Inc.",
    industry: "Power & Grid Equipment",
    marketCap: 279.51,
    revenue: 39.38,
    dayChange: -0.52,
    currentPrice: 1019,
    priceTarget: 1065,
    revenueForecast: [39.4, 42.1, 45.7, 49.8],
    stockForecast: [1019, 1042, 1065, 1110],
    topClients: ["National Grid", "Duke Energy", "Enel", "TenneT", "offshore wind developers"],
    futureCustomers: ["AI data-center utilities", "Grid-hardening programs", "Hydrogen power projects"],
  },
  {
    rank: 4,
    ticker: "RTX",
    name: "RTX Corporation",
    industry: "Aerospace & Defense",
    marketCap: 237.14,
    revenue: 90.37,
    dayChange: -0.39,
    currentPrice: 177,
    priceTarget: 190,
    revenueForecast: [90.4, 95.2, 101.8, 107.9],
    stockForecast: [177, 184, 190, 199],
    topClients: ["U.S. Department of Defense", "NATO governments", "Boeing", "Airbus", "global airlines"],
    futureCustomers: ["Missile-defense coalitions", "Commercial engine aftermarket", "Connected battlespace programs"],
  },
  {
    rank: 5,
    ticker: "BA",
    name: "The Boeing Company",
    industry: "Aerospace & Defense",
    marketCap: 187.11,
    revenue: 92.18,
    dayChange: 2.74,
    currentPrice: 248,
    priceTarget: 265,
    revenueForecast: [92.2, 102.5, 113.2, 122.7],
    stockForecast: [248, 256, 265, 282],
    topClients: ["United Airlines", "Ryanair", "Southwest Airlines", "U.S. Department of Defense", "NASA"],
    futureCustomers: ["Fleet-renewal airlines", "Space launch customers", "Maritime patrol programs"],
  },
  {
    rank: 6,
    ticker: "UNP",
    name: "Union Pacific Corporation",
    industry: "Railroads",
    marketCap: 157.13,
    revenue: 24.7,
    dayChange: -0.09,
    currentPrice: 264,
    priceTarget: 276,
    revenueForecast: [24.7, 25.6, 26.7, 27.8],
    stockForecast: [264, 270, 276, 286],
    topClients: ["Agriculture shippers", "Automotive OEMs", "Intermodal retailers", "Energy producers", "chemical producers"],
    futureCustomers: ["Nearshoring manufacturers", "EV battery supply chains", "Port-to-inland logistics corridors"],
  },
  {
    rank: 7,
    ticker: "ETN",
    name: "Eaton Corporation plc",
    industry: "Electrical Equipment",
    marketCap: 155.91,
    revenue: 28.52,
    dayChange: 0.87,
    currentPrice: 397,
    priceTarget: 424,
    revenueForecast: [28.5, 30.9, 33.8, 36.4],
    stockForecast: [397, 411, 424, 448],
    topClients: ["Schneider Electric partners", "Hyperscale data centers", "utilities", "aerospace OEMs", "industrial facilities"],
    futureCustomers: ["AI data centers", "Grid storage developers", "EV charging networks"],
  },
  {
    rank: 8,
    ticker: "DE",
    name: "Deere & Company",
    industry: "Agricultural Machinery",
    marketCap: 155.27,
    revenue: 46.73,
    dayChange: -0.98,
    currentPrice: 573,
    priceTarget: 594,
    revenueForecast: [46.7, 48.2, 50.1, 52.4],
    stockForecast: [573, 584, 594, 617],
    topClients: ["Large row-crop farms", "construction contractors", "ag co-ops", "rental fleets", "government land agencies"],
    futureCustomers: ["Precision agriculture operators", "Autonomous farm fleets", "Brazilian grain producers"],
  },
  {
    rank: 9,
    ticker: "HON",
    name: "Honeywell International Inc.",
    industry: "Industrial Conglomerates",
    marketCap: 135.04,
    revenue: 37.66,
    dayChange: -1.37,
    currentPrice: 210,
    priceTarget: 232,
    revenueForecast: [37.7, 39.8, 41.6, 43.9],
    stockForecast: [210, 222, 232, 246],
    topClients: ["Airbus", "Boeing", "refineries", "pharma manufacturers", "warehouse automation operators"],
    futureCustomers: ["Process automation upgrades", "Airport modernization programs", "Energy transition projects"],
  },
  {
    rank: 10,
    ticker: "VRT",
    name: "Vertiv Holdings Co",
    industry: "Electrical Equipment",
    marketCap: 130.59,
    revenue: 10.84,
    dayChange: -0.01,
    currentPrice: 342,
    priceTarget: 368,
    revenueForecast: [10.8, 12.7, 15.1, 17.9],
    stockForecast: [342, 355, 368, 392],
    topClients: ["Amazon Web Services", "Microsoft Azure", "Equinix", "Digital Realty", "telecom operators"],
    futureCustomers: ["AI training campuses", "Liquid-cooled data centers", "Sovereign cloud operators"],
  },
  {
    rank: 11,
    ticker: "LMT",
    name: "Lockheed Martin Corporation",
    industry: "Aerospace & Defense",
    marketCap: 116.78,
    revenue: 75.11,
    dayChange: -1.15,
    currentPrice: 499,
    priceTarget: 530,
    revenueForecast: [75.1, 78.6, 82.3, 86.7],
    stockForecast: [499, 516, 530, 548],
    topClients: ["U.S. Department of Defense", "NATO governments", "NASA", "Japan Ministry of Defense", "Australia Department of Defence"],
    futureCustomers: ["Integrated air defense buyers", "Space-security agencies", "F-35 sustainment partners"],
  },
  {
    rank: 12,
    ticker: "PWR",
    name: "Quanta Services, Inc.",
    industry: "Engineering & Construction",
    marketCap: 111.79,
    revenue: 30.12,
    dayChange: -0.76,
    currentPrice: 748,
    priceTarget: 785,
    revenueForecast: [30.1, 33.8, 37.2, 41.4],
    stockForecast: [748, 766, 785, 824],
    topClients: ["U.S. utilities", "renewable developers", "telecom carriers", "pipeline operators", "data-center power buyers"],
    futureCustomers: ["Grid interconnection programs", "Transmission buildouts", "Hydrogen pipeline projects"],
  },
  {
    rank: 13,
    ticker: "PH",
    name: "Parker-Hannifin Corporation",
    industry: "Motion & Control",
    marketCap: 110.81,
    revenue: 20.99,
    dayChange: -0.68,
    currentPrice: 858,
    priceTarget: 902,
    revenueForecast: [21, 22.1, 23.5, 25],
    stockForecast: [858, 880, 902, 941],
    topClients: ["Airbus", "Boeing", "industrial OEMs", "mobile equipment makers", "semiconductor equipment makers"],
    futureCustomers: ["Electric aircraft suppliers", "Factory automation OEMs", "Hydrogen equipment builders"],
  },
  {
    rank: 14,
    ticker: "HWM",
    name: "Howmet Aerospace Inc.",
    industry: "Aerospace Components",
    marketCap: 108.25,
    revenue: 8.62,
    dayChange: -0.68,
    currentPrice: 267,
    priceTarget: 282,
    revenueForecast: [8.6, 9.4, 10.3, 11.1],
    stockForecast: [267, 275, 282, 297],
    topClients: ["GE Aerospace", "Pratt & Whitney", "Rolls-Royce", "Boeing", "Airbus"],
    futureCustomers: ["Next-gen engine programs", "Defense airframe platforms", "Advanced turbine builders"],
  },
  {
    rank: 15,
    ticker: "TT",
    name: "Trane Technologies plc",
    industry: "Building Systems",
    marketCap: 103.05,
    revenue: 21.6,
    dayChange: -0.77,
    currentPrice: 462,
    priceTarget: 486,
    revenueForecast: [21.6, 23, 24.6, 26.4],
    stockForecast: [462, 474, 486, 510],
    topClients: ["Commercial real estate owners", "schools", "healthcare systems", "data centers", "government facilities"],
    futureCustomers: ["Heat-pump retrofits", "Low-carbon campuses", "Cold-chain logistics"],
  },
  {
    rank: 16,
    ticker: "CMI",
    name: "Cummins Inc.",
    industry: "Engines & Power Systems",
    marketCap: 93.77,
    revenue: 33.89,
    dayChange: -0.49,
    currentPrice: 683,
    priceTarget: 718,
    revenueForecast: [33.9, 35.5, 37.7, 40.2],
    stockForecast: [683, 700, 718, 746],
    topClients: ["PACCAR", "Daimler Truck", "Navistar", "Komatsu", "power generation customers"],
    futureCustomers: ["Hydrogen engine fleets", "Microgrid operators", "Low-emission trucking fleets"],
  },
  {
    rank: 17,
    ticker: "GD",
    name: "General Dynamics Corporation",
    industry: "Aerospace & Defense",
    marketCap: 93.57,
    revenue: 53.81,
    dayChange: -0.35,
    currentPrice: 342,
    priceTarget: 366,
    revenueForecast: [53.8, 56.4, 59.9, 63.1],
    stockForecast: [342, 354, 366, 382],
    topClients: ["U.S. Department of Defense", "U.S. Navy", "Gulfstream buyers", "NATO governments", "federal agencies"],
    futureCustomers: ["Submarine programs", "Secure cloud agencies", "Business jet fleet renewals"],
  },
  {
    rank: 18,
    ticker: "FDX",
    name: "FedEx Corporation",
    industry: "Air Freight & Logistics",
    marketCap: 90.33,
    revenue: 91.93,
    dayChange: 0.7,
    currentPrice: 382,
    priceTarget: 405,
    revenueForecast: [91.9, 94.2, 97.5, 101.3],
    stockForecast: [382, 394, 405, 422],
    topClients: ["E-commerce retailers", "healthcare shippers", "SMBs", "international manufacturers", "high-value logistics clients"],
    futureCustomers: ["Healthcare cold-chain", "Cross-border merchants", "Returns logistics platforms"],
  },
  {
    rank: 19,
    ticker: "WM",
    name: "Waste Management, Inc.",
    industry: "Environmental Services",
    marketCap: 86.49,
    revenue: 25.41,
    dayChange: -2.75,
    currentPrice: 215,
    priceTarget: 230,
    revenueForecast: [25.4, 26.8, 28.4, 30.1],
    stockForecast: [215, 222, 230, 241],
    topClients: ["Municipalities", "commercial property owners", "industrial facilities", "retail chains", "event venues"],
    futureCustomers: ["Renewable natural gas buyers", "Recycling compliance programs", "Battery recycling partners"],
  },
  {
    rank: 20,
    ticker: "UPS",
    name: "United Parcel Service, Inc.",
    industry: "Air Freight & Logistics",
    marketCap: 85.66,
    revenue: 88.32,
    dayChange: 0.68,
    currentPrice: 100,
    priceTarget: 113,
    revenueForecast: [88.3, 90.6, 94.1, 98.2],
    stockForecast: [100, 107, 113, 121],
    topClients: ["Amazon", "SMBs", "healthcare shippers", "industrial distributors", "retailers"],
    futureCustomers: ["Healthcare logistics", "SMB cross-border sellers", "Returns management networks"],
  },
  {
    rank: 21,
    ticker: "JCI",
    name: "Johnson Controls International plc",
    industry: "Building Products",
    marketCap: 85.12,
    revenue: 24.43,
    dayChange: 0.19,
    currentPrice: 130,
    priceTarget: 139,
    revenueForecast: [24.4, 25.5, 26.9, 28.2],
    stockForecast: [130, 135, 139, 147],
    topClients: ["Commercial buildings", "hospitals", "schools", "industrial facilities", "government buildings"],
    futureCustomers: ["Smart building retrofits", "Energy performance contracts", "Security modernization programs"],
  },
  {
    rank: 22,
    ticker: "CSX",
    name: "CSX Corporation",
    industry: "Railroads",
    marketCap: 83.3,
    revenue: 14.15,
    dayChange: 0.83,
    currentPrice: 44,
    priceTarget: 48,
    revenueForecast: [14.2, 14.8, 15.6, 16.3],
    stockForecast: [44, 46, 48, 51],
    topClients: ["Intermodal retailers", "auto manufacturers", "agriculture shippers", "chemical producers", "ports"],
    futureCustomers: ["Nearshoring corridors", "Port expansions", "EV supply chain shippers"],
  },
  {
    rank: 23,
    ticker: "EMR",
    name: "Emerson Electric Co.",
    industry: "Automation & Controls",
    marketCap: 79.15,
    revenue: 18.32,
    dayChange: 0.16,
    currentPrice: 139,
    priceTarget: 151,
    revenueForecast: [18.3, 19.7, 21.2, 22.9],
    stockForecast: [139, 145, 151, 160],
    topClients: ["Process manufacturers", "energy producers", "life sciences plants", "chemical producers", "utilities"],
    futureCustomers: ["Digital plant operators", "LNG expansions", "Battery materials facilities"],
  },
  {
    rank: 24,
    ticker: "NOC",
    name: "Northrop Grumman Corporation",
    industry: "Aerospace & Defense",
    marketCap: 78.05,
    revenue: 42.37,
    dayChange: -0.5,
    currentPrice: 544,
    priceTarget: 575,
    revenueForecast: [42.4, 44.3, 46.9, 49.1],
    stockForecast: [544, 560, 575, 592],
    topClients: ["U.S. Department of Defense", "U.S. Air Force", "NASA", "intelligence agencies", "allied governments"],
    futureCustomers: ["Space defense programs", "Autonomous systems buyers", "Strategic deterrence programs"],
  },
  {
    rank: 25,
    ticker: "CP",
    name: "Canadian Pacific Kansas City Limited",
    industry: "Railroads",
    marketCap: 76.32,
    revenue: 10.73,
    dayChange: 0.96,
    currentPrice: 82,
    priceTarget: 89,
    revenueForecast: [10.7, 11.7, 12.8, 14],
    stockForecast: [82, 86, 89, 94],
    topClients: ["Agriculture shippers", "automotive OEMs", "intermodal logistics", "energy producers", "Mexico-U.S. trade lanes"],
    futureCustomers: ["Nearshoring manufacturers", "Cross-border auto supply chains", "Grain export corridors"],
  },
];

export const recentIndustrialDeals: IndustrialDeal[] = [
  {
    id: "hon-wws",
    acquirer: "American Industrial Partners",
    target: "Honeywell Warehouse and Workflow Solutions",
    ticker: "HON",
    value: "Undisclosed",
    date: "Apr 2026",
    status: "Signed",
    rationale: "Corporate carve-out of a warehouse automation business with about $935M of 2025 revenue.",
  },
  {
    id: "hon-sundyne",
    acquirer: "Honeywell",
    target: "Sundyne",
    ticker: "HON",
    value: "$2.16B",
    date: "Jun 2025",
    status: "Completed",
    rationale: "Adds engineered pumps and compressors for refining, petrochemicals, LNG, and renewable fuels.",
  },
  {
    id: "ph-filtration",
    acquirer: "Parker-Hannifin",
    target: "Filtration Group",
    ticker: "PH",
    value: "$9.25B",
    date: "2026",
    status: "Announced",
    rationale: "Expands filtration exposure across life sciences, indoor air quality, and industrial process markets.",
  },
  {
    id: "flowserve-chart",
    acquirer: "Flowserve / Baker Hughes interest",
    target: "Chart Industries",
    value: "$19B+ situation",
    date: "2025-2026",
    status: "Contested",
    rationale: "Industrial gas, LNG, and energy-transition equipment consolidation.",
  },
  {
    id: "tdg-simmonds",
    acquirer: "TransDigm",
    target: "Simmonds Precision Products from RTX",
    ticker: "RTX",
    value: "$765M",
    date: "Q4 2025",
    status: "Completed",
    rationale: "Aerospace component portfolio reshaping and aftermarket-focused acquisition.",
  },
];

export const financeApiProviders = [
  {
    name: "Finnhub",
    env: "FINNHUB_API_KEY",
    bestFor: "Best free primary source for live/near-live U.S. quotes, price targets, and analyst recommendations",
  },
  {
    name: "Alpha Vantage",
    env: "ALPHA_VANTAGE_API_KEY",
    bestFor: "Free fallback for latest quotes, company overview data, and analyst target price fields",
  },
  {
    name: "FactSet",
    env: "FACTSET_API_KEY",
    bestFor: "Enterprise market data, fundamentals, estimates, ownership, segments, and deal intelligence",
  },
];

export function getCompany(ticker: string) {
  return topIndustrialCompanies.find((company) => company.ticker === ticker) ?? topIndustrialCompanies[0];
}

export function formatBillions(value: number) {
  return `$${value.toLocaleString(undefined, { maximumFractionDigits: 2 })}B`;
}
